[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "lywsd03mmc-plotly-graph"
version = "0.1.0"
description = "Plugin to add LYWSD03MMC temperature and humidity sensor data to PlotlyTempGraph"
authors = [
    {name = "yutaka551", email = "yutaka551butaman@gmail.com"}
]
readme = {file = "README.md", content-type = "text/markdown"}
license = {text = "MIT"}

requires-python = ">=3.7, <4"

dependencies = [
    "lywsd03mmc>=0.1.0"
]

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
include = [
    "lywsd03mmc_plotly_graph",
    "lywsd03mmc_plotly_graph.*"
]

[project.entry-points."octoprint.plugin"]
lywsd03mmc_plotly_graph = "lywsd03mmc_plotly_graph"

[project.urls]
Homepage = "https://github.com/yutaka551/lywsd03mmc-plotly-graph"
