[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "OctoPrint-PlotlyGraph-LYWSD03MMC"
version = "0.1.0"
description = "Plugin to add LYWSD03MMC temperature and humidity sensor data to PlotlyTempGraph"
authors = [
    {name = "yutaka551", email = "yutaka551butaman@gmail.com"}
]
readme = {file = "README.md", content-type = "text/markdown"}
license = {text = "MIT"}

requires-python = ">=3.7, <4"

dependencies = [
    "lywsd03mmc>=0.1.0"
]

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
include = [
    "octoprint_plotly_graph_lywsd03mmc",
    "octoprint_plotly_graph_lywsd03mmc.*"
]

[project.entry-points."octoprint.plugin"]
plotly_graph_lywsd03mmc = "octoprint_plotly_graph_lywsd03mmc"

[project.urls]
Homepage = "https://github.com/yutaka551/lywsd03mmc-plotly-graph"
